version: '3'

services:
  node0:
    container_name: pylonsnode
    build:
      context: .
      args:
        - BINARY_VERSION=v0.4.2
    # command: test_node_deploy.sh
    command: test_upgrade_node_deploy.sh
    ports:
      - "26657:26657"
      - "1317:1317"
    volumes:
      - ./debug:/debug